#-------------------------------
# General Site Settings

title: Gianna
logo: 
author: Gianna Barnhart
description: Welcome to my website!
email: giannabarnhart@gmail.com
phone: +207 522 65 78
address: Winooski, VT, USA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Gianna

social:
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/giannabarnhart/"}
- {icon: "ti-instagram", link: "https://www.instagram.com/gianna_o2/"}


#-------------------------------
# About (Section and Page)

# About Section
blurb: Champlain College | Class of 2021 | Bachelor of Science <br> Digital Marketing, Project Management, Organizational Development & HR

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Content Design, color: '#fdb157', value: '80%'}
- {name: Digital Marketing, color: '#9473e6', value: '70%'}
- {name: Leadership & Career Coaching, color: '#bdecf6', value: '50%'}
- {name: Project Management, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Digital Marketing & Administrative Specialist, icon: 'icon-1.png', date: 'Dec 2019 - Current', organization: 'Evolution PT & Yoga'}
- {name: Peer Financial & Career Coach, icon: 'icon-2.png', date: 'Aug 2020 - Current', organization: 'Champlain College'}
- {name: Research Coordination, icon: 'icon-3.png', date: 'Dec 2018 - Sept 2019', organization: 'Univerity of Vermont'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: B.S Integrated Studies, date: '2019 - 2021', organization: 'Champlain College | Burlington, VT'}
- {name: B.S. Neuroscience, date: '2017 - 2019', organization: 'University of Vermont | Burlington, VT'}
- {name: High School, date: '2017', organization: 'Brunswick High School | Brunswick, ME'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Art and Photography,
    icon: ti-palette,
    description: 'Art has always been a big, often therapeutic, part of my life. I studied art through my senior year of high school and still enjoy it my free time. Art takes many forms in my life, whether on a canvas, piece of paper, computer screen, through a camera lense, and in everyday life.', 
    active: # Add true to select section
  }
- {
    name: Advocacy and Career Coaching,
    icon: ti-heart,
    description: 'I love helping people solve everyday problems, like <strong>finding jobs, accessing educational opportunities, navigating the medical world, and finding community/social support services.</strong> I've taken on advocacy roles professionally, as well as in my personal. ',
    active: # Add true to select section
   }
- {
    name: Research,
    icon: ti-search,
    description: 'I really enjoy research which is what originally drew me to the sciences. I have experience reading and interpreting scientific writing, as well as confucting studies and working in a lab environment. These days, I find myself looking into international events, social issues, and technology.',
    active: # Add true to select section
  }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Gemma"
    image: "assets/images/testimonial/gemma.HEIC"
    designation : "My great pyrenees mix rescue."
    content : "Gemma seems to think she is a person. She is incredibly smart and very communicative, but also a giant goofball. She has an uncanny ability to communicate what she wants. Her and Athena both enjoy bird watching and hanging out under beds together. She is definitely the annoying little sister, but her and Clara love each other to pieces."
    
  - name: "Clara"
    image: "assets/images/testimonial/clara.HEIC"
    designation: "My black lab and oldest child."
    content: "Clara was trained as a service dog to help me when I faint (I do that a lot... long story) but is now enjoying a comfy early retirement after an intestinal issue requiring massive surgery. She saved my mother's life getting help from a neighbor when my mother collapse outside due to a stomach rupture. She demands and receives all the attention and love."
    
  - name: "Athena"
    image: "assets/images/testimonial/athena.HEIC"
    designation: "Techincally my roommate's cat but CEO of the house."
    content: "Technically my roommate's cat but I was the one to pick her up from a gas station. She was rescued when her mother gave birth to her on a kind family's deck in the middle of a snowstorm.  Athena grew up with my dogs and is, <strong>100% the boss</strong> of them. She introduced the dogs to cat tv—sitting on top of the couch and watching birds at the window bird feeders."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com

