---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: gianna-barnhart/_pages
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: ".html"
- type: directory
  path: gianna-barnhart/assets/images
  label: images
  create: all
  match: "**/*"
- type: document
  path: gianna-barnhart/_projects
  label: Projects
- type: jekyll-posts
  label: Posts
  create: all
  new_doc_ext: blog
- type: jekyll-pages
  label: Index
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
