---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _layouts
  label: layouts
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: _data
  label: data
  create: all
  match: "**/*"
  new_doc_ext: yml
- type: directory
  path: _includes
  label: includes
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: _pages
  label: pages
  create: all
  match: "**/*"
  new_doc_ext: html
- type: jekyll-posts
  label: Posts
  create: all
  new_doc_ext: blog
- type: jekyll-pages
  label: Index
  create: all
upload_dir: assets
public_path: "/assests/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundler   jekyll   jekyll-sitemap   wdm (>= 0.1.0)
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
