---
label: Project
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: title
- name: image_upload
  type: image_gallery
  config: {}
  label: image upload
- name: text
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: text
- name: tags
  type: tag_list
  default: []
  label: tags
pages:
- _pages/project-1.html
